### ISSUE TITLE
Module not found: Error: Cannot resolve module 'vue-geb' in ...

### ISSUE THREAD

**Issue by LarryEitel** [vouill/vue-geb#1]
Any idea why I am getting:

`Module not found: Error: Cannot resolve module 'vue-geb' in ...`

I'm using:

`import geb from 'vue-geb'`

I successfully installed the example. But I am trying to wire up to an existing project. I have same vue/vuex version installed.

Thank You

**Comment by vouill** [comment]
Hey !

What is your `vue-geb` version in your package.json?

**Comment by LarryEitel** [comment]
"vue-geb": "^0.2.0",

**Comment by LarryEitel** [comment]
Same version as in your example.

**Comment by vouill** [comment]
That's weird, i have tried a fresh clean installation and it does find the module.

Are you using webpack ? if not what are you using ?
What is your vue version?

Finally can you check the content of `./node_modules/vue-geb/lib `, is it empty ?

**Comment by LarryEitel** [comment]
Away from my desk.
I am using webpack.
Lib is not empty. If I import directly from lib I get no import error
however then when I click on button to view modal, I get some kind of error
like invalid action type.
Back to my desk in couple of hours.

**Comment by vouill** [comment]
Hum, indeed in the example i make a useless commit action in Vuex (i just removed it, so now no errors should be logged), nice catch. Good thing it had nothing to do with the library itself.

If you are able to import it directly, it means it comes from your webpack configuration. 
I ll try to import vue-geb from a basic webpack configuration to see if i can repro or spot the issue.

Vouill.

**Comment by vouill** [comment]
Update vue-geb and try it now, i have uploaded a hotfix. The issue came from the main attribute of the package.json.

Keep me updated !

**Comment by LarryEitel** [comment]
I am now getting:

`[vuex] unknown mutation type: open_modal` when I click on a button to pop open the modal.

In this case I added your example Hello.vue into my project.

**Comment by LarryEitel** [comment]
```
(unknown) [vuex] unknown mutation type: open_modal
commit
```

**Comment by LarryEitel** [comment]
in `store.js`
```
  actions: {
    open_modal: ({commit}, payload) => {
      commit('open_modal', payload)
      gebHandler.emit(payload)
    }
  },
```

**Comment by vouill** [comment]
Yes this issue is fixed if you pull again the example. i was simply committing an useless commit action. I removed it few hours ago :) 
I am closing this issue then, reopen it if you still get the `Cannot resolve module` error again.

**Comment by LarryEitel** [comment]
Sorry, but now I have no error but nor does a modal pop up when I click the buttons. :(

Your example works but not when I add to my project. Perhaps some conflict. Don't see any errors. Don't have time to further diagnose the issue. 

Looks promising. :)

**Comment by vouill** [comment]
@LarryEitel The modal uses Bulma CSS. It's not plug and play as it is, i will make one soon if thats what you are looking for. 
However you can still use vue-geb to trigger your current modal ( if you have one ) and you should be able to open it from anywhere :).
 Feel free to open an issue if you have trouble implementing it in your project.
